### ISSUE TITLE
How to repurpose this repos for C# binding to GDExtension of GDMP?

### ISSUE THREAD

**Issue by GeorgeS2019** [antonWetzel/GDExtensionCSharp#1]
```
[configuration]

entry_symbol = "mediapipe_library_init"

[libraries]

linux.debug.x86_64 = "res://addons/GDMP/libs/x86_64/libGDMP.so"
linux.release.x86_64 = "res://addons/GDMP/libs/x86_64/libGDMP.so"
windows.debug.x86_64 = "res://addons/GDMP/libs/x86_64/GDMP.dll"
windows.release.x86_64 = "res://addons/GDMP/libs/x86_64/GDMP.dll"
```

**Comment by GeorgeS2019** [comment]
@antonWetzel 

This is [WIP how to possibly doing it](https://github.com/j20001970/GDMP-demo/discussions/6#discussioncomment-6029012)

**Comment by antonWetzel** [comment]
I wrote these bindings to see how the API works.
I do not plan to maintain the bindings at the moment and probably won't in the future.

I think (with limited knowledge) that the best solution is
- generate bindings in for csharp which call into the registered functions
```csharp
namespace GDMP {
    class SomeCoolObject {
        private GD.Object data;
         
        public SomeCoolObject() { this.data = GD.Instantiate("GDMPSomeCoolObject"); }

        public SomeType SomeFunction() {
            return (SomeType)this.data.call("some_function");
        }
    }
}
```
- I have no clue how to Godot API calls should look like (`GD.Object`, `GD.Instantiate`, ...) are just guesses, but I think the functionality should exist.
- if the API from GDMP is small
    - manually write a csharp bindings
- else
   - write own bindings generator
   - this repository might be used to see how bindings can be generated, but better solutions should be searched first

**Comment by GeorgeS2019** [comment]
[Possible to create C# binding for GDExtension?](https://github.com/godotengine/godot-proposals/discussions/7024)
